#!/bin/sh -

DIR=$(git rev-parse --show-toplevel)/other

# install global vim config to make sudoedit etc easier to work with
if [ -e $DIR/vim/vimrc.local ]; then
  sudo ln -sf $DIR/vim/vimrc.local /etc/vim/
fi

# install docker daemon file to change root dir, the root db partition
# fills up too quickly with images
if [ -e $DIR/docker/daemon.json ]; then
  [ ! -d ~/.docker_data ] && mkdir ~/.docker_data
  sudo ln -sf $DIR/docker/daemon.json /etc/docker/
fi
