#!/bin/sh -

DIR=$(git rev-parse --show-toplevel)/other

# install docker daemon file to change root dir, the root db partition
# fills up too quickly with images
if [ -e $DIR/docker/daemon.json ]; then
  [ ! -d ~/.docker_data ] && mkdir ~/.docker_data
  sudo ln -sf $DIR/docker/daemon.json /etc/docker/
fi
