#!/bin/bash
conf_dir=$HOME/.config
stow_dirs=( "irb" "pry" "tmux" "zsh" "git")

if ! type stow >/dev/null; then
  echo "stow is not installed, please install and retry" >&2
  exit 1
fi

for i in "${stow_dirs[@]}"
do
  echo "intalling ${i}"
  stow --dotfiles $i
done

echo "installing nvim"
nvim_dir=$conf_dir/nvim

[[ ! -d $nvim_dir ]] && mkdir --parents $nvim_dir
stow --target $nvim_dir nvim

echo "installing pycodestyle"
stow --target $conf_dir pycodestyle
