#!/bin/bash
stow_dirs=( "bash" "irb" "pry" "tmux" "vim" "zsh" )
os=$(uname)

if type stow >/dev/null; then
  for i in "${stow_dirs[@]}"
  do
    stow $i
  done
else
  echo "stow is not installed, please install and retry"
fi
  
if [ $os = "Darwin" ]; then
  $(cd brew && brew install)
fi
