#!/bin/env zsh
# cdr navigates back to the root directory of a git project

local dir=$(git rev-parse --show-toplevel 2> /dev/null)
if [ -z "$dir" ]; then
  echo "top level git directory not found"
  return 1
fi
cd $dir
