#! /bin/env zsh
# return the name of the main branch in git repo

command git rev-parse --git-dir &>/dev/null || return
local ref
for ref in refs/{heads,remotes/{origin,upstream}}/{main,trunk,mainline,default}; do
  if command git show-ref -q --verify $ref; then
    echo ${ref:t}
    return
  fi
done
echo master
