#!/bin/env zsh
# wod() returns the Word of the Day from Wordnik. 
# If an "-f" option is provided then the word of the day is fetched again.
emulate -L zsh
setopt pipefail err_return

if [ -z "$WORDNIK_API_KEY" ]; then
  echo "wod: Wordnik API key not set" >&2
  return 1
fi

if ! hash jq 2> /dev/null; then
  echo "wod: jq not installed" >&2
  return 1
fi

# store wod in a dot file so we only need to request it once a day
local file_path=$XDG_CACHE_HOME/wod

wod_not_updated_today() {
  local date_fmt="+%Y%m%d"
  [[ "$(date -r $file_path $date_fmt)" < "$(date $date_fmt)" ]]
}

if [ "$1" != "-f" ] && wod_not_updated_today; then
  cat $file_path
  return 0
fi

# let's just assume the request works
local resp=$(curl -s "https://api.wordnik.com/v4/words.json/wordOfTheDay?api_key=$WORDNIK_API_KEY")

local word=$(jq '.word' <<< "$resp")
local kind=$(jq '.definitions[0].partOfSpeech // ""' <<< "$resp" | sed -e 's/"//g')
local def=$(jq '.definitions[0].text' <<< "$resp" | sed 's/"//g')
local note=$(jq '.note' <<< $resp | sed 's/"//g')

cat <<-END | fmt | tee $file_path
  Word of the day: $fg[red]${word}$fg[default] ${kind:+- $kind}

  Definition: $fg[green]$def$fg[default]
  $note
END
